#! /bin/bash
roomtemp1=($(cat /sys/bus/w1/devices/28-0316644ee8ff/w1_slave | grep  -E -o ".{0,0}t=.{0,5}" | cut -c 3-)/1000)
roomtemp2=expr ($(cat /sys/bus/w1/devices/28-0416637613ff/w1_slave | grep  -E -o ".{0,0}t=.{0,5}" | cut -c 3-))/1000
echo "Temperature: $roomtemp1"
echo "Temperature: $roomtemp2"

